#!/bin/sh -v
#
# Prepares distribution to be in the usual
# state for running './configure', 'make' and
# 'make install'

autoreconf -f -i -s

./configure --prefix=$TRM_SOFTWARE/local
make install
make
